# Generated by Django 3.1.4 on 2020-12-03 08:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='موقعیت جغرافیایی')),
                ('service', models.IntegerField(verbose_name='محدوده سرویس دهی')),
            ],
            options={
                'verbose_name_plural': 'رستوران ها',
            },
        ),
    ]
