# Generated by Django 3.1.4 on 2020-12-03 08:44
from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path
import random

DATA_FILENAME = 'export.json'


def load_data(apps, schema_editor):
    restaurant = apps.get_model('geolocation', 'RestaurantModel')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objtype = obj['type']
                if objtype == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    territory = random.randrange(1000, 5001, 500)
                    restaurant(name=name, location=location, service=territory).save()
            except KeyError:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
